
spring:
  profiles: local
  application:
    name: LOCAL-POC-microservice
  ###
  #   Database Settings
  ###
  datasource:
    url: jdbc:h2:mem:example-app;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true

# The base path for our services.
service:
  context: /v1
  
springfox:
  documentation:
    swagger:
      v2:
        path: /docs/swagger

app:
  config:
    accountsConfig:
      -  
        accountType: SAVINGS
        allowedTransactions:
          - DEPOSIT
          - WITHDRAWAL
          - PAY_INTEREST
      - 
        accountType: CHECKING
        allowedTransactions:
          - DEPOSIT
          - WITHDRAWAL
          - CASH_TRANSFER
        
server:
  port: 10101
  #enable https/ssl , only for dev
  ssl:
    key-store: classpath:keystore-local.p12
    key-store-password: tomcat
    keyStoreType: PKCS12
    keyAlias: tomcat